### ISSUE TITLE
Difference AX-51 and AX-61

### ISSUE THREAD

**Issue by yogiTruth** [tarik0/bsc-fullnode-installer#6]
Thank you for replying so quickly, I have one more question. what is the difference AX-51 and AX-61, I see it is the CPU, one being Octa-Core and the second 12 Core. So I wanted to know what affect it would have on the node and should I buy the latter?

**Comment by tarik0** [comment]
Well obviously It has more specs then the other but you don't have to buy the best one as long as 51 does the job.
